ALTER TABLE attendance
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'PRESENT';

UPDATE attendance
SET status = CASE WHEN is_present = TRUE THEN 'PRESENT' ELSE 'ABSENT' END;

ALTER TABLE attendance
    ADD COLUMN IF NOT EXISTS note VARCHAR(500);
