CREATE TABLE IF NOT EXISTS promotion_decision (
    id INT NOT NULL AUTO_INCREMENT,
    student_id INT NOT NULL,
    source_enrollment_id INT NOT NULL,
    source_classroom_id INT NOT NULL,
    destination_classroom_id INT NULL,
    previous_academic_year_id INT NOT NULL,
    next_academic_year_id INT NULL,
    outcome VARCHAR(30) NOT NULL,
    decision_date DATE NOT NULL,
    decision_reason VARCHAR(500) NOT NULL,
    processed_by VARCHAR(100) NOT NULL,
    attendance_percentage DECIMAL(5,2) NULL,
    attendance_recorded_days INT NOT NULL DEFAULT 0,
    examination_average DECIMAL(5,2) NULL,
    examination_subject_count INT NOT NULL DEFAULT 0,
    remarks VARCHAR(1000) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    created_by VARCHAR(255) NULL,
    updated_by VARCHAR(255) NULL,
    PRIMARY KEY (id),
    INDEX idx_promotion_student (student_id),
    INDEX idx_promotion_source_enrollment (source_enrollment_id),
    INDEX idx_promotion_source_classroom (source_classroom_id),
    CONSTRAINT fk_promotion_student FOREIGN KEY (student_id) REFERENCES student(id),
    CONSTRAINT fk_promotion_source_enrollment FOREIGN KEY (source_enrollment_id) REFERENCES enrollment(id),
    CONSTRAINT fk_promotion_source_classroom FOREIGN KEY (source_classroom_id) REFERENCES classroom(id),
    CONSTRAINT fk_promotion_destination_classroom FOREIGN KEY (destination_classroom_id) REFERENCES classroom(id),
    CONSTRAINT fk_promotion_previous_year FOREIGN KEY (previous_academic_year_id) REFERENCES academic_year(id),
    CONSTRAINT fk_promotion_next_year FOREIGN KEY (next_academic_year_id) REFERENCES academic_year(id)
);
